services:
  sapphire-hotel:
    depends_on:
      - db
    container_name: sapphire-hotel
    image: sapphire-hotel:latest
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    command: ['sh', '-c', 'sleep 10 && npm run start:dev:docker']
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgresql://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@${CONTAINER_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?schema=public

  db:
    image: postgres:16.2
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

volumes:
  postgres-data:
